### ISSUE TITLE
Where to download ContosoRealEstateCustomControls_managed.zip from?

### ISSUE THREAD

**Issue by tsileo-wdi** [scottdurow/magical-mystery-tour#1]
In the README at: https://github.com/scottdurow/magical-mystery-tour/blob/eca34c9429c2d13b642c18c255e95cc03eb2f901/docs/00-full-development-setup-instructions.md?plain=1#L522

It's not clear to me where we are supposed to download the solution zip file from?

**Comment by scottdurow** [comment]
Great point - I'll add clearer instructions. You can download from here https://github.com/scottdurow/magical-mystery-tour/releases?q=ContosoRealEstateCustomControls&expanded=true

**Comment by scottdurow** [comment]
Fixed in https://github.com/microsoft/contoso-real-estate-power-platform
