### ISSUE TITLE
Power Platform Environment or Azure Environment?

### ISSUE THREAD

**Issue by tsileo-wdi** [scottdurow/magical-mystery-tour#2]
Re this line:  https://github.com/scottdurow/magical-mystery-tour/blob/eca34c9429c2d13b642c18c255e95cc03eb2f901/docs/00-full-development-setup-instructions.md?plain=1#L461C5-L461C81

I think (but maybe I'm wrong?) this is creating an Azure Environment, not a Power Platform Environment?

**Comment by scottdurow** [comment]
Thank you for pointing this out!

**Comment by scottdurow** [comment]
Fixed in https://github.com/microsoft/contoso-real-estate-power-platform
